### ISSUE TITLE
Where are the products in the CATEGORIES on the CMS 

### ISSUE THREAD

**Issue by Stellyclothing** [Stellyclothing/Stelly-New-Website#15]
HI I'm unable to find any products in the category 
I would go to on our front page : Clothes - Dress - Casual & DO the same thing on the CMS but unable to find any products .

Thank You 
![screen shot 2015-06-16 at 6 45 19 pm](https://cloud.githubusercontent.com/assets/9522928/8179229/b86c820a-1458-11e5-9e50-1ca10fd370d7.png)

JOSh

**Comment by supremesupports** [comment]
Actually, Products will be found in **Catalog >> Products** in your prestashop back-end. To add new product, you'll find "Add New Product" option on top bar.

If you enter to any **Category**, you will only see the **sub-categories** under that specific category. Products are in a different menu in **Prestashop version 1.6**. Hope you get it.

Thanks.

**Comment by Stellyclothing** [comment]
Hi ,
I'm in the product categories and in one of the sub categories and unable to find any products on there.

Im not quite sure what you meant ? 

Thank You

**Comment by supremesupports** [comment]
If you go to **Catalog >> Categories**, you will only see the list of **Categories** & **Sub-categories**.

To view the Products, you will need to go to **Catalog >> Products**.

![catalog-products](https://cloud.githubusercontent.com/assets/12905649/8180067/2dd21d32-143d-11e5-96f2-d3c279eea38b.png)

Let me know if you still don't get it.

Thank you.

**Comment by Stellyclothing** [comment]
Hi , 
I got it, its a bit different to the current prestashop 
Is there a reason why ? easier to manage ? I just find it a little bit more confusing

Category only there to create new category and sub category but not a place to manage products ?

Thanks for your help 

Josh

**Comment by supremesupports** [comment]
Yes, this is different from previous prestashop version. We don't think we can combine Categories & Products in new prestashop version because it's default setting.

You'll need to assign categories from **Catalog > Products**. Please click on a product to edit, then follow this screenshot to assign that product into specific category.

![edit products](https://cloud.githubusercontent.com/assets/12905649/8199030/b3723fba-14d0-11e5-8cb4-e495531e728f.png)


Thanks!
